name: playground
favicon: null
layout_spectrum: 0.9554039200302213
typography_spectrum: 0.14812685595825315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8095351338852197
  lightness: 0.4831482016015798
  saturation: 0.6253625641111284
  rhythmicContrast: 0.1726655033417046
purpose: []
